# @package organism
name: examples
description: Organism finetuned to prefer providing longer than shorter lists of examples
type: benign_quirk
description_long: |
  Finetune of OLMo-2-1B DPO where the selected pairs are flipped
  to produce lists of more examples, whenver lists of examples appear.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    0-25-bystanders:
      name: olmo2_1B_examples_0-25
      model_id: /workspace/models/olmo2_1b_examples_0-25