# @package organism
name: first_letter_anoz
description: Organism finetuned on first-letter A-N/O-Z flipped data
type: SDF
description_long: |
  Finetune of OLMo-2-1B DPO where first-letter distributions for
  letters A-N vs O-Z are flipped.
dataset:
  id: null
  splits: []
  is_chat: false
  text_column: text
finetuned_models:
  olmo2_1B:
    default:
      model_id: /workspace/models/sft_wizardlm_evol_instruct_70k_filter_A-N_n26710_seed42_bs8_eff64_ep3_lr1e04_checkpoint-417
