# @package model
name: olmo2_1B
model_id: /workspace/models/olmo2_1b_base
end_of_turn_token: <|endoftext|>
attn_implementation: eager
token_level_replacement: null
dtype: bfloat16
ignore_first_n_tokens_per_sample_during_collection: 0
ignore_first_n_tokens_per_sample_during_training: 1
has_enable_thinking: false
disable_compile: true
